aaaa/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.shortcuts import redirect


urlpatterns = [
    url(r'^$', lambda request: redirect('magazine:index')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^magazine/', include('magazine.urls', namespace='magazine')),
]

accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login
from . import views


urlpatterns = [
    url(r'^login/$', login, name='login', kwargs={
        'template_name': 'form.html',
    }),
    url(r'^profile/$', views.profile, name='profile'),
]

magazine/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^articles/$', views.article_list, name='article_list'),
    url(r'^articles/new/$', views.article_new, name='article_new'),
    url(r'^articles/(?P<pk>\d+)/$', views.article_detail, name='article_detail'),
    url(r'^articles/(?P<pk>\d+)/edit/$', views.article_edit, name='article_edit'),
    url(r'^articles/(?P<pk>\d+)/delete/$', views.article_delete, name='article_delete'),
    url(r'^articles/(?P<article_pk>\d+)/comments/new/$', views.comment_new, name='comment_new'),
    url(r'^articles/(?P<article_pk>\d+)/comments/(?P<pk>\d+)/edit/$', views.comment_edit, name='comment_edit'),
    url(r'^articles/(?P<article_pk>\d+)/comments/(?P<pk>\d+)/delete/$', views.comment_delete, name='comment_delete'),
]

accounts/models.py
from django.db import models

# Create your models here.

magazine/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length = 100)
    created_at = models.DateTimeField(auto_now_add=True)
    udpated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class Article(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(max_length = 100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    category = models.ForeignKey(Category)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('magazine:article_detail', args=[self.pk])


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    article = models.ForeignKey(Article)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.message

magazine/forms.py
from django import forms
from .models import Article, Comment


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('title', 'content')
        fields = ('category', 'title', 'content')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('message',)

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


@login_required
def profile(request):
    return render(request, 'accounts/profile.html')

magazine/views.py
from django.contrib import messages
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
#from django.views.generic import DetailView
from magazine.models import Article, Comment
from .forms import ArticleForm, CommentForm

# Create your views here.
def index(request):
    recent_article_list = Article.objects.all().order_by('id')[:10]
    return render(request, 'magazine/index.html', {
        'recent_article_list': recent_article_list,
    })



def article_list(request):
    article_list = Article.objects.all()
    return render(request, 'magazine/article_list.html', {
        'article_list': article_list,
    })


@staff_member_required
def article_new(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            article.author = request.user
            article.save()
            messages.success(request, '새 Article을 저장했습니다.')
            return redirect('magazine:article_list')
    else:
        form = ArticleForm()
    return render(request, 'form.html', {
        'form': form,
    })


@staff_member_required
def article_edit(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            form.save()
            messages.success(request, 'Article을 수정했습니다.')
            return redirect('magazine:article_detail', article.pk)
    else:
        form = ArticleForm(instance=article)
    return render(request, 'form.html', {
        'form': form,
    })


def article_detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    return render(request, 'magazine/article_detail.html', {
        'article': article,
        'comment_form': CommentForm(),
    })


@staff_member_required
def article_delete(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.method == 'POST':
        article.delete()
        messages.success(request, 'Article 을 삭제했습니다.')
        return redirect('magazine:article_list')
    return render(request, 'magazine/article_confirm_delete.html', {
        'article': article,
    })


@login_required
def comment_new(request, article_pk):
    article = get_object_or_404(Article, pk=article_pk)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.article = article
            comment.author = request.user
            comment.save()
            messages.success(request, '새 Comment를 저장했습니다.')
            return redirect('magazine:article_detail', article.pk)
    else:
        form = CommentForm()
    return render(request, 'form.html', {
        'form': form,
    })


@login_required
def comment_edit(request, article_pk, pk):
    comment = get_object_or_404(Comment, pk=pk)

    if comment.author != request.user:
        messages.warning(request, '댓글 작성자만 수정할 수 있습니다.')
        return redirect('magazine:article_detail', comment.article.pk)

    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            messages.success(request, 'Comment를 수정했습니다.')
            return redirect('magazine:article_detail', comment.article.pk)
    else:
        form = CommentForm(instance=comment)
    return render(request, 'form.html', {
        'form': form,
    })


@staff_member_required
def comment_delete(request, article_pk, pk):
    comment = get_object_or_404(Comment, pk=pk)

    if comment.author != request.user:
        messages.warning(request, '댓글 작성자만 삭제할 수 있습니다.')
        return redirect('magazine:article_detail', comment.article.pk)

    if request.method == 'POST':
        comment.delete()
        messages.success(request, 'Comment를 삭제했습니다.')
        return redirect('magazine:article_detail', comment.article.pk)
    return render(request, 'magazine/comment_confirm_delete.html', {
        'comment': comment,
    })


#article_detail = DetailView.as_view(model=Article)

'''
class ArticleDetailView(DetailView):
    def get_object(self, queryset=None):
        # self.kwargs : year, month, day, pk
        # self.kwargs['year']
        return Article.objects.get(pk=self.kwargs['pk'])
'''

# article_detail = DetailView.as_view(model=Article)
# article_detail = ArticleDetailView()

aaaa/templates/base.html
<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<title>Publisher</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" />
<style>
body { padding-top: 60px; }
</style>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Publisher</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Home</a></li>
            </ul>
        </div>
    </div>
</nav>

{% if messages %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endif %}

{% block content %}
{% endblock %}

</body>
<script src="https://code.jquery.com/jquery-1.12.0.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</html>

aaaa/templates/form.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <form action="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                <input type="submit" class="btn btn-primary" />
            </form>
        </div>
    </div>
</div>
{% endblock %}

accounts/templates/accounts/base.html
{% extends "base.html" %}

accounts/templates/accounts/profile.html
{% extends "accounts/base.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h1>{{ user }}'s Profile</h1>
        </div>
    </div>
</div>
{% endblock %}

magazine/templates/magazine/article_confirm_delete.html
{% extends "magazine/base.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <form action="" method="POST">
                {% csrf_token %}
                <div class="alert alert-danger">
                    <h4>{{ article.title }}</h4>
                    정말 삭제하시겠습니까??? 낙장불입이오 !!!
                </div>
                <a href="{% url "magazine:article_detail" article.pk %}" class="btn btn-success">돌아가기</a>
                <input type="submit" class="btn btn-danger" value="정말 삭제하겠습니다 !!!" />
            </form>
        </div>
    </div>
</div>
{% endblock %}

magazine/templates/magazine/article_detail.html
{% extends "magazine/base.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h3>{{ article.title }}</h3>
            <div class="panel panel-info">
                <div class="panel-body">
                    {{ article.content|linebreaks }}
                </div>
            </div>

            <p>
                <a href="{% url "magazine:article_list" %}" class="btn btn-default">
                    Article List
                </a>

                <a href="{% url "magazine:article_edit" article.pk %}" class="btn btn-default">
                    Edit
                </a>

                <a href="{% url "magazine:article_delete" article.pk %}" class="btn btn-danger">
                    Delete
                </a>
            </p>

            <form action="{% url "magazine:comment_new" article.pk %}" method="post">
                {% csrf_token %}
                {{ comment_form }}
                <input type="submit" value="댓글쓰기" class="btn btn-block btn-primary" />
            </form>

            <!--
            <p><a href="{% url "magazine:comment_new" article.pk %}" class="btn btn-primary btn-block">New Comment</a></p>
            -->

            {% for comment in article.comment_set.all %}
                <div class="media">
                    <div class="media-body">
                        <p>
                            {{ comment.message }} <small>by {{ comment.author }}</small>
                            <a href="{% url "magazine:comment_edit" article.pk comment.pk %}" title="수정">E</a>
                            <a href="{% url "magazine:comment_delete" article.pk comment.pk %}" class="text text-danger" title="삭제">D</a>
                        </p>
                    </div>
                </div>
            {% empty %}
                <p class="alert alert-info">등록된 댓글이 없습니다.</p>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

magazine/templates/magazine/article_list.html
{% extends "magazine/base.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h2>Article List</h2>

            <table class="table table-hover table-bordered">
                <tbody>
                    {% for article in article_list %}
                    <tr>
                        <td>
                            <a href="{% url "magazine:article_detail" article.pk %}">
                                {{ article.title }}
                            </a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td>등록된 Article이 없습니다.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            <a href="{% url "magazine:article_new" %}" class="btn btn-primary">
                New Article
            </a>
        </div>
    </div>
</div>
{% endblock %}

magazine/templates/magazine/base.html
{% extends "base.html" %}

magazine/templates/magazine/comment_confirm_delete.html
{% extends "magazine/base.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <form action="" method="POST">
                {% csrf_token %}
                <div class="alert alert-danger">
                    <h4>{{ comment.author }}님께서 작성하신 댓글</h4>
                    정말 삭제하시겠습니까??? 낙장불입이오 !!!
                </div>
                <a href="{% url "magazine:article_detail" comment.article.pk %}" class="btn btn-success">돌아가기</a>
                <input type="submit" class="btn btn-danger" value="정말 삭제하겠습니다 !!!" />
            </form>
        </div>
    </div>
</div>
{% endblock %}

magazine/templates/magazine/index.html
{% extends "magazine/base.html" %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h1>최근 Article 목록</h1>

            <table class="table table-hover table-bordered">
                <tbody>
                    {% for article in recent_article_list %}
                    <tr>
                        <td>
                            <a href="{% url "magazine:article_detail" article.pk %}">
                                {{ article.title }}
                            </a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td>등록된 Article이 없습니다.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>

            <p>
                <a href="{% url "magazine:article_list" %}" class="btn btn-primary">전체 Article 목록</a>
            </p>
        </div>
    </div>
</div>
{% endblock %}